### ISSUE TITLE
Make code font size configurable

### ISSUE THREAD

**Issue by ysshah** [BoostIO/BoostNote-Legacy#1005]
I would like to be able to change the font size of the code in the `<code>` and `<pre>` elements in the preview. The default is a little too big for my taste (I think it's 14px right now?) - I would like mine to be 12px.

**Comment by kazup01** [comment]
Hi @ysshah , you can change the font size at Preference.
Preferences -> UI -> Preview Font Size
![screen shot 0029-10-23 at 10 03 54 am](https://user-images.githubusercontent.com/8602615/31868418-9c139d38-b7d9-11e7-98a0-4b8255ea5e23.png)

**Comment by ysshah** [comment]
Yes, this changes the font size of the entire preview, but if I decrease this then the regular text becomes too small for me. I would like a way to change **only** the font size of the code. If I'm the only user who wants this, then it's okay :)

**Comment by paulojraposo** [comment]
I second @ysshah request. Great software you've got here, everyone :)
