### ISSUE TITLE
Nim Syntax 

### ISSUE THREAD

**Issue by ire4ever1190** [BoostIO/BoostNote-Legacy#3631]
# Current behavior

cannot use nim in code block

# Expected behavior
```nim
echo("test")
```
should have the highlighting for nim

1.  open a note
2.  write code block for nim

# Environment

- Boostnote version: 0.4.1
- OS version and name: Android Oreo

**Comment by Flexo013** [comment]
We use CodeMirror for syntax highlighting. To support this we would need to add a new mode as suggested here:  
https://github.com/codemirror/CodeMirror/issues/6165
