### ISSUE TITLE
Home and End position for wrapped lines

### ISSUE THREAD

**Issue by huettenhain** [BoostIO/BoostNote-Legacy#689]
On Windows (which is what I use), most editors that wrap lines (like Notepad) will move the cursor to the beginning of the wrapped line when pressing the `POS1` key. Even the textarea that I am writing this in right now behaves exactly like that. It is quite comfortable, because it allows you to navigate quickly to the middle of a long, wrapped text. In Boostnote however, pressing `POS1` will move the cursor to the beginning of the actual line, which might be the beginning of the paragraph if you are just writing a lot of text which is wrapped. 

Is there any way this could be changed or toggled? Something like a "soft" versus "hard" line break option?

**Comment by Flexo013** [comment]
Confirmed that this behavior still occurs for snippet notes in 0.12.0 on Windows 10.
